feat: localazy integration (#4)
* feat: localazy integration

* updated language files

* portuguese lang code rename

* move arb files

* update localazy.json config file

* moved localazy.json config & fixed pt-PT error

Exception: Arb file for a fallback, pt, does not exist, even though
the following locale(s) exist: [pt_PT].
When locales specify a script code or country code, a
base locale (without the script code or country code) should
exist as the fallback. Please create a {fileName}_pt.arb
file.

* fixed @@locale key error in app_pt.arb

Generating synthetic localizations package failed with 1 error:

Exception: The locale specified in @@locale and the arb filename do not match.
Please make sure that they match, since this prevents any confusion
with which locale to use. Otherwise, specify the locale in either the
filename of the @@locale key only.
Current @@locale value: pt_PT
Current filename extension: pt

* rerun localization gen with key transformer script

* updated README.md, changed UI

* README.md fix

* clean up

* update documentation