moved localazy.json config & fixed pt-PT error
Exception: Arb file for a fallback, pt, does not exist, even though
the following locale(s) exist: [pt_PT].
When locales specify a script code or country code, a
base locale (without the script code or country code) should
exist as the fallback. Please create a {fileName}_pt.arb
file.