fixed @@locale key error in app_pt.arb
Generating synthetic localizations package failed with 1 error:

Exception: The locale specified in @@locale and the arb filename do not match.
Please make sure that they match, since this prevents any confusion
with which locale to use. Otherwise, specify the locale in either the
filename of the @@locale key only.
Current @@locale value: pt_PT
Current filename extension: pt